{% set name = "mangum" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mangum-{{ version }}.tar.gz
  sha256: dafd45692fb74bbdaad44d32afc07ed393f6f9e6150b880b5b78d0c4cd0f392b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - mangum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jordaneremieff/mangum
  summary: AWS Lambda support for ASGI applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
